before_install:
- curl -Lo /tmp/pandoc-latest.deb `curl -s https://api.github.com/repos/jgm/pandoc/releases/latest
  | grep 'browser_' | grep '\.deb' | cut -d\" -f4`
- sudo dpkg -i /tmp/pandoc-latest.deb

language: ruby
rvm:
- 2.2

notifications:
  email: false

env:
  global:
  - secure: k4DgPm3217H/4cxjpFNGu3ZxnY4QyZ6f8GTl/3TBnmNXiAB/xosOOHj+vRDbndbdS1S3MKy9MoUCtKGHk9IY06m1fUeP0NfHI94h8DDsQZIl1jQ8z6QWsNjZjQi8/DJQC5CGMuLf2MkytU12bfpR0in9x82fDgAWoYp1XvaTlkcDCmZhjWvGW7AveNUAybOmOpBewjjParG/169DO5MzdrznWanlqwEQ9JJoLLWnlHpchIMtLH+V52fwLSohLDx63gzdDOLAVr7EvNRn3zrK4RysTMF7o+Ma/CZW4vPw/6smJ2m4MJNvXoMbJrvf1Hext4OhECaZFCH3mIMNbN4idFH9/HIUJzqv7k7ajNyVhAYceo+tzdpBYz+q75RtWNJ9wS+LjFylyFgygJMg0tAMUpIz3AX08NfWYiCjylDdqRSVI9SBInoVvEsb7H2VfmcORns0T551teCVVWAsh0NUo3ickBqMjBAbBWJjcUhN31I40bdcO2ndxVXObW7aog5WifJhOYRz1Eyl7xWl7D6EA7jDa9AB8JSvl/HdFSQZsC1e4x46IA2D0Rpau0Kv6ETdr2+1pvdP4DnZZaNQcQ172c2wggUMPSm0JiD/SSo7ZU8HWNKT+yBKn0+pm6pBgKVdg/uKK7qfDVY2beGSvDJMQsxAljk/VSsai4axQWdS4Fc=
